// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/Games": {
    params: {};
  };
  "/Shopping": {
    params: {};
  };
  "/Register": {
    params: {};
  };
  "/Signin": {
    params: {};
  };
  "/google/redirect": {
    params: {};
  };
  "/Account": {
    params: {};
  };
  "/Checkout": {
    params: {};
  };
  "/OrderComplete": {
    params: {};
  };
  "/admin/CreateGame": {
    params: {};
  };
  "/admin/UpdateGame": {
    params: {};
  };
  "/admin/DeleteGame": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/Games" | "/Shopping" | "/Register" | "/Signin" | "/google/redirect" | "/Account" | "/Checkout" | "/OrderComplete" | "/admin/CreateGame" | "/admin/UpdateGame" | "/admin/DeleteGame";
  };
  "routes/Homepage.tsx": {
    id: "routes/Homepage";
    page: "/" | "/Games" | "/Shopping" | "/Register" | "/Signin" | "/google/redirect";
  };
  "routes/Index.tsx": {
    id: "routes/Index";
    page: "/";
  };
  "routes/Games.tsx": {
    id: "routes/Games";
    page: "/Games";
  };
  "routes/Shopping.tsx": {
    id: "routes/Shopping";
    page: "/Shopping";
  };
  "routes/Register.tsx": {
    id: "routes/Register";
    page: "/Register";
  };
  "routes/Signin.tsx": {
    id: "routes/Signin";
    page: "/Signin";
  };
  "routes/GoogleRedirect.tsx": {
    id: "routes/GoogleRedirect";
    page: "/google/redirect";
  };
  "routes/AuthLayout.tsx": {
    id: "routes/AuthLayout";
    page: "/Account" | "/Checkout" | "/OrderComplete";
  };
  "routes/Account.tsx": {
    id: "routes/Account";
    page: "/Account";
  };
  "routes/Checkout.tsx": {
    id: "routes/Checkout";
    page: "/Checkout";
  };
  "routes/OrderComplete.tsx": {
    id: "routes/OrderComplete";
    page: "/OrderComplete";
  };
  "routes/admin/AdminLayout.tsx": {
    id: "routes/admin/AdminLayout";
    page: "/admin/CreateGame" | "/admin/UpdateGame" | "/admin/DeleteGame";
  };
  "routes/admin/CreateGame.tsx": {
    id: "routes/admin/CreateGame";
    page: "/admin/CreateGame";
  };
  "routes/admin/UpdateGame.tsx": {
    id: "routes/admin/UpdateGame";
    page: "/admin/UpdateGame";
  };
  "routes/admin/DeleteGame.tsx": {
    id: "routes/admin/DeleteGame";
    page: "/admin/DeleteGame";
  };
};